name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies (skip husky scripts)
        run: npm install --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Size budget check (200 KB gzipped)
        run: |
          SIZE=$(find dist/assets -type f -name "*.js" -exec gzip -c {} + | wc -c)
          echo "Bundle size (gzipped): $SIZE bytes"
          if [ "$SIZE" -gt 204800 ]; then
            echo "Bundle exceeds 200 KB limit" && exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_DISABLE_GIT: 1
        with:
          slug: atxbrianbehm/randomizer-public
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/v8/coverage-final.json
          flags: unittests
          fail_ci_if_error: true
